apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mario
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - mario.example.com
  rules:
    - host: mario.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: mario
              servicePort: http
