provisioner:
  common:
    #
    # Defines whether to generate rbac roles
    #
    rbac:
      # rbac.create: `true` if rbac resources should be created
      create: true
      # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
      pspEnabled: true

  classes:
    - name: minio-disks # Defines name of storage classe.
      # Path on the host where local volumes of this storage class are mounted
      # under.
      hostDir: /mnt/minio-disks/
      # Optionally specify mount path of local volumes. By default, we use same
      # path as hostDir in container.
      # mountDir: /mnt/fast-disks
      # The volume mode of created PersistentVolume object. Default to Filesystem
      # if not specified.
      volumeMode: Filesystem
      # Filesystem type to mount.
      # It applies only when the source path is a block device,
      # and desire volume mode is Filesystem.
      # Must be a filesystem type supported by the host operating system.
      fsType: ext4
      # File name pattern to discover. By default, discover all file names.
      namePattern: "*"
      blockCleanerCommand:
        #  Do a quick reset of the block device during its cleanup.
        # - "/scripts/quick_reset.sh"
        #  or use dd to zero out block dev in two iterations by uncommenting these lines
        #  - "/scripts/dd_zero.sh"
        #  - "2"
        # or run shred utility for 2 iteration.s
        # - "/scripts/shred.sh"
        # - "2"
      # or blkdiscard utility by uncommenting the line below.
      #  - "/scripts/blkdiscard.sh"
      # Uncomment to create storage class object with default configuration.
      #storageClass: true
      # Uncomment to create storage class object and configure it.
      storageClass:
        reclaimPolicy: Retain # Available reclaim policies: Delete/Retain, defaults: Delete.
      # isDefaultClass: true # set as default class
