apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m

spec:
  tls:
    - hosts:
        - docker-registry.demo.dev.sspcloud.fr
  rules:
    - host: docker-registry.demo.dev.sspcloud.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: registry
              servicePort: http

